#-------------------------------
# General Site Settings

title: Inverse Lattice
logo: 
author: Saurabh Sugandh
description: Details about Saurabh
email: mrsauravs@gmail.com
phone: +91 9535 791 480
address: Bengaluru, Karnataka, India
copyright: Copyright &copy; 2020 Designed by Saurabh Sugandh

menu:
- {name: Docs, link: 'https://docs.inverselattice.com'}
- {name: Blog, link: 'https://blog.inverselattice.com'}
- {name: Opinion, link: 'https://opinion.inverselattice.com'}
- {name: Resume, link: '<iframe src="http://docs.google.com/gview?url=https://github.com/mrsauravs/site/blob/master/sugandh_saurabh_India.pdf&embedded=true" style="width:100%; height:1000px;" frameborder="0"></iframe>'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I'm Saurabh Sugandh. <br> Take a look around to discover me. </br>

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
blurb:
  Experienced in information gathering, business analysis, networking, documentation, and leading projects. I constantly work to improve user-content experience and closely work on various initiatives at my workplace. Iâ€™ve a sound knowledge of computer networks. I occasionally ponder over various linux flavors to satisfy my curiousity.
  
#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Markdown, color: '#90f067', value: '100%'}
- {name: DITA XML, color: '#67f0d7', value: '90%'}
- {name: oXygen XML Editor, color: '#f0ee67', value: '80%'}
- {name: PTC Arbortext Editor, color: '#fc8b3a', value: '70%'}
- {name: Git, color: '#fc473a', value: '60%'}
- {name: SDL Trisoft/KC, color: '#3adffc', value: '50%'}
- {name: Adobe Acrobat, color: '#3a74fc', value: '40%'}
- {name: Adobe InDesign, color: '#bb3afc', value: '30%'}


#-------------------------------
# Experience Section

experience-title: Experience
experience:
- {name: Senior Technical Writer, icon: 'informatica.png', date: 'Jul 2019 - Present', organization: 'Informatica'}
- {name: Technical Writer 3, icon: 'sophos.jpg', date: 'Jun 2017 - Jul 2019', organization: 'Sophos'}
- {name: Senior Technical Associate, icon: 'avaya.jpg', date: 'Jan 2015 - Apr 2017', organization: 'Avaya'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Master of Technology in Computer Science, icon: 'bit.png', date: '2016', organization: 'Birla Institute of Technology'}
- {name: Bachelor of Engineerng in Mechanical, icon: 'shivaji.jpg', date: '2009', organization: 'Shivaji University'}


#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: mrsauravs@gmail.com
